# Generated by Django 3.1.8 on 2022-05-11 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('pwd', models.CharField(max_length=255)),
                ('video_watching_counts', models.FloatField()),
                ('video_watching_seconds', models.FloatField()),
                ('course_discuss_related', models.FloatField()),
                ('course_discuss_unrelated', models.FloatField()),
                ('discuss_topic_numbers', models.FloatField()),
                ('discussion_comment_and_reply_numbers', models.FloatField()),
                ('spoc_score', models.FloatField()),
                ('test_mean', models.FloatField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xadmin.class')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('pwd', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='class',
            name='tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xadmin.teacher'),
        ),
    ]
