# Generated by Django 3.1.8 on 2022-05-11 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xadmin', '0002_auto_20220511_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['id'], 'verbose_name': 'ClassTable', 'verbose_name_plural': 'ClassTable'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['id'], 'verbose_name': 'StudentTable', 'verbose_name_plural': 'StudentTable'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['id'], 'verbose_name': 'TeacherTable', 'verbose_name_plural': 'TeacherTable'},
        ),
        migrations.AlterModelTable(
            name='class',
            table='class',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='teacher',
        ),
    ]
