# Generated by Django 3.1.8 on 2022-05-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xadmin', '0003_auto_20220511_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
