# Generated by Django 3.1.8 on 2022-05-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xadmin', '0004_student_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='advice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
